### ISSUE TITLE
Fix for import on Python 2.7.9

### ISSUE THREAD

**Issue by Winter-Silence** [dimka665/awesome-slugify#28]
awesome-slugify 1.6.5

```
Traceback (most recent call last):
  File "py_parsers.py", line 12, in <module>
    from slugify import slugify
  File "/usr/local/lib/python2.7/dist-packages/slugify/__init__.py", line 2, in <module>
    from slugify.main import Slugify, UniqueSlugify
ImportError: No module named main
```

**Comment by alemol** [comment]
The same issue for 2.7.6

**Comment by jonafato** [comment]
#22 fixes this issue.
