### ISSUE TITLE
Fix for Python 2.7.10

### ISSUE THREAD

**Issue by janislejins** [dimka665/awesome-slugify#29]
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import slugify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/slugify/__init__.py", line 2, in <module>
    from slugify.main import Slugify, UniqueSlugify
ImportError: No module named main

**Comment by jonafato** [comment]
#22 fixes this issue.

**Comment by jonafato** [comment]
Looks like #22 has been merged, so this issue can be closed.
